export const site = {
  name: '王江涛',
  nameEn: 'Jiangtao Wang',
  title: '数据闭环 / 评测算法',
  titleEn: 'Autonomous Driving Data & Evaluation Engineer',
  description: 'Focused on replay systems, scenario mining, evaluation infrastructure, and simulation workflows for autonomous driving data closed-loop systems.',
  email: 'colawang1997@outlook.com',
  phone: '15235991939',
  github: 'https://github.com/cola1917',
  location: '北京',
  university: '莫纳什大学 (QS36)',
  universityEn: 'Monash University',
  degree: '数据科学硕士',
  degreeEn: 'Master of Data Science',
};
